
# SMLFS programming language v0.1

%%inline
def concat(xs):
  if len(xs) == 1:
    return xs[0]
  res = []
  for x in xs:
    res.extend(x)
  return res

def importName(x):
  return x.split('.')[-1]

def inc(x):
  return x + 1
%%

%include "to_include.py"

list[p] : p         { [$1] }
        | list[p] p { $1.append($2); $1 }
        ;

sep_list[comma, p]
        : p                          { [$1] }
        | sep_list[comma, p] comma p { $1.append($3); $1 }
        ;

START : <BOF> toplevel <EOF> { $2 };

toplevel : 'module' nameStr
           list[import]
           list[declaration]
           { ModuleRecord($2, $3, concat($4)) }
          | 'module' nameStr
           list[declaration]
           { ModuleRecord($2, [], concat($3)) } ;

import : 'import' nameStr 'as' nameStr
          { ($2, $4) }
       | 'import' nameStr
          { ($2, importName($2)) }
        ;

tvar    : <name> { TVar($1.value) };

toptype : 'forall' list[nameStr] '.' toptype { TForall($2, $4) }
        |  arrowtype  { $1 }
        ;

arrowtype : calltype '->' toptype { TArrow($1, $3) }
          | calltype { $1 }
          ;

calltype : calltype type { TApp($1, $2) }
         | type          { $1 }
         ;

nameStr : <name> { $1.value };

type : tvar { $1 }
     | '(' ')'                        { TTup([]) }
     | '(' sep_list[',', toptype] ')' { mk_tuple(TTup, $2) }
     | '{' toptype '}' { TImplicit($2) }
     | <str> { TSym(parse_str($1.value)) }
     | '@' <name> { TNew($2.value) }
     | '?' type 'as' nameStr   { TQuery($4, $2) }
     ;


type_head :  <name> list[nameStr] { (Pos($1), $1.value, $2) }
          |  <name> { (Pos($1), $1.value, []) }
          ;

record_def : '(' sep_list[',', record_field_def] ')' { (0, $2) }
           | '(' ')' { (0, []) }
           ;

record_field_def : nameStr ':' toptype { (Pos($2), $1,  $3) };

adt_def : list[variant_def] { (1, $1) };

variant_def : '|' nameStr toptype ':' toptype { (Pos($1), $2, $3, $5) };

declaration : 'val' <name> ':' toptype
            { [DLoc(Pos($1)), DAnn($2.value, $4)] }
          | 'let' <name> '=' expr
            { [DLoc(Pos($1)), DBind($2.value, $4)] }
          | 'check' nameStr 'as' nameStr
            { [DLoc(Pos($1)), DQuery($4, $2)] }
          | 'open' expr
            { [DLoc(Pos($1)), DOpen($2)] }
          | 'type' type_head '=' (record_def | variant_def)
            { mk_type_def($2, $4) }

          ;

expr : 'if' expr 'then' expr 'else' expr
       { EITE($2, $4, $6) }
     | list[declaration] 'in' expr
       { ELet(concat($1), $3) }
     | 'fun' <name> '->' expr
       { EFun($2.value, $4) }
     | 'coerce' expr { ECoerce($2) }
     | call { $1 }
     ;

call : call atom { EApp($1, $2) }
     | atom { $1 }
     ;

atom : 'extern' <str> { EExt(parse_str($2.value))  }
     | '(' sep_list[',', expr] ')'
       { mk_tuple(ETup, $2) }
     | '(' ')' { ELoc(Pos($1), ETup([])) }
     | <int> { EVal(I64(int($1.value))) }
     | <float> { EVal(F64(float($1.value))) }
     | <name> { EVar($1.value) }
     | <str> { EVal(Str(parse_str($1.value))) }
     | 'true' { EVal(Bl(True)) }
     | 'false' { EVal(Bl(False)) }
     | atom '.' nameStr
      { EField($1, $3) }
     | '?'  atom 'as' nameStr
      { EQuery($4, $2) }
     ;
